CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL,
    senha_hash VARCHAR(255) NOT NULL,
    perfil VARCHAR(20) NOT NULL DEFAULT 'ALUNO',
    xp_total INTEGER NOT NULL DEFAULT 0,
    nivel INTEGER NOT NULL DEFAULT 1,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_usuarios PRIMARY KEY (id),
    CONSTRAINT ck_usuarios_nome_nao_vazio CHECK (BTRIM(nome) <> ''),
    CONSTRAINT ck_usuarios_email_nao_vazio CHECK (BTRIM(email) <> ''),
    CONSTRAINT ck_usuarios_senha_hash_nao_vazia CHECK (BTRIM(senha_hash) <> ''),
    CONSTRAINT ck_usuarios_perfil CHECK (perfil IN ('ALUNO', 'ADMINISTRADOR')),
    CONSTRAINT ck_usuarios_xp_total CHECK (xp_total >= 0),
    CONSTRAINT ck_usuarios_nivel CHECK (nivel >= 1)
);

CREATE UNIQUE INDEX uk_usuarios_email
    ON usuarios (LOWER(email));
