CREATE TABLE questoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    categoria_id BIGINT NOT NULL,
    enunciado TEXT NOT NULL,
    explicacao TEXT NOT NULL,
    dificuldade VARCHAR(10) NOT NULL,
    xp_base INTEGER NOT NULL,
    ativa BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_questoes PRIMARY KEY (id),
    CONSTRAINT fk_questoes_categoria
        FOREIGN KEY (categoria_id) REFERENCES categorias (id),
    CONSTRAINT ck_questoes_enunciado_nao_vazio CHECK (BTRIM(enunciado) <> ''),
    CONSTRAINT ck_questoes_explicacao_nao_vazia CHECK (BTRIM(explicacao) <> ''),
    CONSTRAINT ck_questoes_dificuldade
        CHECK (dificuldade IN ('FACIL', 'MEDIO', 'DIFICIL')),
    CONSTRAINT ck_questoes_xp_base CHECK (xp_base > 0)
);

CREATE INDEX idx_questoes_categoria
    ON questoes (categoria_id);

CREATE INDEX idx_questoes_filtro
    ON questoes (categoria_id, dificuldade, ativa);
