CREATE TABLE alternativas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    questao_id BIGINT NOT NULL,
    texto TEXT NOT NULL,
    correta BOOLEAN NOT NULL DEFAULT FALSE,
    ordem SMALLINT NOT NULL,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_alternativas PRIMARY KEY (id),
    CONSTRAINT fk_alternativas_questao
        FOREIGN KEY (questao_id) REFERENCES questoes (id),
    CONSTRAINT uk_alternativas_questao_ordem UNIQUE (questao_id, ordem),
    CONSTRAINT uk_alternativas_id_questao UNIQUE (id, questao_id),
    CONSTRAINT ck_alternativas_texto_nao_vazio CHECK (BTRIM(texto) <> ''),
    CONSTRAINT ck_alternativas_ordem CHECK (ordem > 0)
);

CREATE INDEX idx_alternativas_questao
    ON alternativas (questao_id);
