CREATE TABLE tentativas_questao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id BIGINT NOT NULL,
    questao_id BIGINT NOT NULL,
    alternativa_id BIGINT NOT NULL,
    correta BOOLEAN NOT NULL,
    xp_concedido INTEGER NOT NULL DEFAULT 0,
    respondida_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_tentativas_questao PRIMARY KEY (id),
    CONSTRAINT fk_tentativas_questao_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios (id),
    CONSTRAINT fk_tentativas_questao_questao
        FOREIGN KEY (questao_id) REFERENCES questoes (id),
    CONSTRAINT fk_tentativas_questao_alternativa
        FOREIGN KEY (alternativa_id, questao_id)
        REFERENCES alternativas (id, questao_id),
    CONSTRAINT ck_tentativas_questao_xp_concedido CHECK (xp_concedido >= 0)
);

CREATE INDEX idx_tentativas_questao_usuario
    ON tentativas_questao (usuario_id);

CREATE INDEX idx_tentativas_questao_usuario_data
    ON tentativas_questao (usuario_id, respondida_em);

CREATE INDEX idx_tentativas_questao_usuario_questao
    ON tentativas_questao (usuario_id, questao_id);
