spring:
  application:
    name: backend
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/questly}
    username: ${DB_USERNAME:postgres}
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
